# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    build:
      context: ./
      dockerfile: Docker/dev/bdd/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zythologue
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - zythologue

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    networks:
      - zythologue
  backend:
      build:
        context: ./ # Replace this with the path to your Spring Boot app directory
        dockerfile: Docker/dev/api/Dockerfile # Replace this with the path to your Spring Boot app's Dockerfile
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/zythologue
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
      depends_on:
        - db
      develop:
        watch:
          - action: rebuild
            path: ./minimal_api
      networks:
        - zythologue
configs:
  pgpass:
    content: db:5432:*:yokoko:motdepasse
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "Docker",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "yokoko",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

volumes:
  db-data:

networks:
  zythologue: