CREATE USER yokoko WITH PASSWORD 'motdepasse';
GRANT ALL PRIVILEGES ON DATABASE zythologue TO yokoko;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO yokoko;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO yokoko;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO yokoko;
GRANT ALL PRIVILEGES ON SCHEMA public TO yokoko;